#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;


namespace MyNantTestApplication	
{
	public partial class Person
	{
		private int _businessEntityID;
		public virtual int BusinessEntityID 
		{ 
		    get
		    {
		        return this._businessEntityID;
		    }
		    set
		    {
		        this._businessEntityID = value;
		    }
		}
		
		private string _personType;
		public virtual string PersonType 
		{ 
		    get
		    {
		        return this._personType;
		    }
		    set
		    {
		        this._personType = value;
		    }
		}
		
		private bool _nameStyle;
		public virtual bool NameStyle 
		{ 
		    get
		    {
		        return this._nameStyle;
		    }
		    set
		    {
		        this._nameStyle = value;
		    }
		}
		
		private string _title;
		public virtual string Title 
		{ 
		    get
		    {
		        return this._title;
		    }
		    set
		    {
		        this._title = value;
		    }
		}
		
		private string _firstName;
		public virtual string FirstName 
		{ 
		    get
		    {
		        return this._firstName;
		    }
		    set
		    {
		        this._firstName = value;
		    }
		}
		
		private string _middleName;
		public virtual string MiddleName 
		{ 
		    get
		    {
		        return this._middleName;
		    }
		    set
		    {
		        this._middleName = value;
		    }
		}
		
		private string _lastName;
		public virtual string LastName 
		{ 
		    get
		    {
		        return this._lastName;
		    }
		    set
		    {
		        this._lastName = value;
		    }
		}
		
		private string _suffix;
		public virtual string Suffix 
		{ 
		    get
		    {
		        return this._suffix;
		    }
		    set
		    {
		        this._suffix = value;
		    }
		}
		
		private int _emailPromotion;
		public virtual int EmailPromotion 
		{ 
		    get
		    {
		        return this._emailPromotion;
		    }
		    set
		    {
		        this._emailPromotion = value;
		    }
		}
		
		private string _additionalContactInfo;
		public virtual string AdditionalContactInfo 
		{ 
		    get
		    {
		        return this._additionalContactInfo;
		    }
		    set
		    {
		        this._additionalContactInfo = value;
		    }
		}
		
		private string _demographics;
		public virtual string Demographics 
		{ 
		    get
		    {
		        return this._demographics;
		    }
		    set
		    {
		        this._demographics = value;
		    }
		}
		
		private Guid _rowguid;
		public virtual Guid Rowguid 
		{ 
		    get
		    {
		        return this._rowguid;
		    }
		    set
		    {
		        this._rowguid = value;
		    }
		}
		
		private DateTime _modifiedDate;
		public virtual DateTime ModifiedDate 
		{ 
		    get
		    {
		        return this._modifiedDate;
		    }
		    set
		    {
		        this._modifiedDate = value;
		    }
		}
		
	}
}
